import type { Metadata } from "next";
import "@/app/globals.css";
import { Sidebar } from "@/components/sidebar";
import { LayoutDashboard, LogOut, Package, ShoppingCart } from "lucide-react";
import { Roboto } from "next/font/google";
import { twMerge } from "tailwind-merge";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "400", "900"],
});

export default function PagesLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={twMerge(
          "bg-gray-900 h-screen text-gray-200 p-3 flex gap-3",
          roboto.className
        )}
      >
        <Sidebar>
          <Sidebar.List className="flex-1">
            <Sidebar.List.Item icon={LayoutDashboard} href="/">
              Dashboard
            </Sidebar.List.Item>
            <Sidebar.List.Item icon={Package} href="/products">
              Products
            </Sidebar.List.Item>
            <Sidebar.List.Item icon={ShoppingCart} href="/sales">
              Sales
            </Sidebar.List.Item>
          </Sidebar.List>
          <Sidebar.List>
            <Sidebar.List.Item
              icon={LogOut}
              href="/auth/sign-out"
              className="text-red-500 hover:bg-red-500/15"
            >
              Sign Out
            </Sidebar.List.Item>
          </Sidebar.List>
        </Sidebar>
        {children}
      </body>
    </html>
  );
}
